### PR TITLE
Fix setup.py so that install via pip works

### PR DESCRIPTION
**Pull request by nixon**
Create a src/github symbolic link that points to the src/ directory so
that distutils can find the files.

http://docs.python.org/distutils/setupscript.html

"""
If you use a different convention to lay out your source directory,
that's no problem: you just have to supply the package_dir option to
tell the Distutils about your convention. For example, say you keep all
Python source under lib, so that modules in the "root package"
(i.e., not in any package at all) are in lib, modules in the foo package
are in lib/foo, and so forth. Then you would put

  package_dir = {'': 'lib'}

in your setup script.  The keys to this dictionary are package names,
and an empty package name stands for the root package. The values are
directory names relative to your distribution root. In this case, when
you say packages = ['foo'], you are promising that the file
lib/foo/**init**.py exists.
"""

### CODE REVIEW

**Comment by nixon** [comment]
This is similiar to issue #41 except it uses a symlink instead of renaming the directory.

**Comment by nixon** [comment]
I should also add that I'm a packaging novice... I just hacked around until I got something that worked for me.

**Comment by dustin** [comment]
Thanks.  :)

**Comment by jtriley** [comment]
Although this works, I still prefer to be able to do the following in any Python package's source folder:

$ git clone git://github.com/dustin/py-github.git
$ cd py-github
$ ipython
$ import github

This way I can play around with the package without needing to install it globally or even in a new virtual env.

This doesn't work currently because the source files are under src instead of github. I'll fork and pull request with the necessary changes unless anyone has objections? Will also test that pip install from github works before a pull request... 

~Justin

**Comment by finn** [comment]
Yes, this resolves issue #41 as well so I closed it, although I agree with jtriley that changing the directory structure might still be preferable.

**Pull request merged**
